### ISSUE TITLE
 wireless crafting grid in curios slot locks hotbar

### ISSUE THREAD

**Issue by Quezler** [refinedmods/refinedstorageaddons#70] opened 2021-08-12 08:16 UTC
> relayed from https://github.com/NillerMedDild/Enigmatica6/issues/2964

**Comment by Darkere** [comment] 2021-08-12 08:26
Duplicate of https://github.com/refinedmods/refinedstorage/issues/3048

**Closed** 2021-08-12 08:39 UTC
